### ISSUE TITLE
Incorrect font sizes

### ISSUE THREAD

**Issue by GreenImp** [CedericPrivat/tailwindcss-base-font-size#36]
I like the idea of this plugin, and it seems to work really well for reworking all of the general padding / margin / etc classes.

However, I've found that it seems to break the relative sizes of the font classes, and they are no longer related to the base font I've set with the plugin.

For example, if I set the base to `10px` as default:

```javascript
  plugins: [
      require('tailwindcss-base-font-size'),
  ],
```

It correctly sets the general font size to `10px`. But, if I try to use any of the font size classes, they are too large.

For example, I would expect the `.font-base` class to be `1rem` / `10px`, but it actually gives me `1.6rem`.
And `.text-sm` is `1.4rem`, which makes it larger than the general font size of `10px`. Without this plugin, the `text-sm` font size is `0.875rem`. If this stayed the same, I think it would be correct.
I'm assuming that the same issue occurs for the large font sizes as well (ie. `text-lg`, `text-xl`).

I was hoping that I could make all of the general font `10px` and still use the `.text-sm` for smaller text.

Is this expected behaviour, or a bug?

**Comment by GreenImp** [comment]
As a workaround, I've found that extending the theme, and specifying the font sizes as the default theme's font sizes seems  to do the trick:

```javascript
const defaultTheme = require('tailwindcss/defaultTheme')

export default {
  theme: {
    extend: {
      fontSize: defaultTheme.fontSize,
    },
  },
  plugins: [
      require('tailwindcss-base-font-size'),
  ],
}
```

**Comment by CedericPrivat** [comment]
Hey @GreenImp, thanks for reaching out! This is actually the intended behavior.

This plugin tries to solve the issue of having to calculate arbitrary values on a base font size of 16px, which is way harder than just moving the decimal point and using 10px as a base font size. But if you still wanted to keep the relative sizes of tailwind's default values, you would need to manually overwrite all of them. 

For example, the default px value for the `.font-base` class is 16px (1rem with a base font size of 16px). To keep the same size of the text with a base font size of 10px you actually need to use 1.6rem, which the plugin correctly sets.

If you want to keep the same relative sizes for margins, paddings etc. expect for fonts, you can always extend the tailwind theme, like you mentioned in your workaround.

Hope that helps!
